import TimeLinePage from '@/Components/TimeLine';
import React from 'react';

export const metadata = {
    title: "KeenKeeper || Timeline",
    description: "Generated by create next app",
};

const TimelineMainPage = () => {
    return (
        <div>
            <TimeLinePage/>
        </div>
    );
};

export default TimelineMainPage;