import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Footer";
import Providers from "./lib/providers";
import { Bounce, ToastContainer } from "react-toastify";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html
            data-theme="light"
            lang="en"
            className={`${geistSans.variable} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col bg-[#f8fafcFF]">
                <Providers>
                    <Navbar />
                    {children}
                    <Footer />
                    <ToastContainer
                        position="top-center"
                        autoClose={2000}
                        hideProgressBar
                        newestOnTop
                        closeOnClick={false}
                        rtl={false}
                        pauseOnFocusLoss={false}
                        draggable={false}
                        pauseOnHover={false}
                        theme="light"
                        transition={Bounce}
                    />
                </Providers>
            </body>
        </html>
    );
}
